export { default as Navbar } from "./Components/Navbar";
export { default as MainPage } from "./Components/MainPage";
export { default as MoviesCard } from "./Components/MoviesCard";
export { default as MovieTrailers } from "./Components/TVShows";
export { default as Loader } from "./Components/Loader";
export { default as ShowsCard } from "./Components/ShowsCard";
export { default as TVShows } from "./Components/TVShows";
export { default as MovieSlider } from "./Components/MovieSlider";
export { default as Footer } from "./Components/Footer";
